### ISSUE TITLE
Maven build failure

### ISSUE THREAD

**Issue by I044433** [SAP-samples/s4hana-ext-migrate-historical-data#1]
Hello,

I followed the steps as listed here (https://help.sap.com/viewer/1eeef7f3c5c140b1a3b406cf357f316a/SHIP/en-US/c14d5cebde124a33b7b8f37f2cbb116a.html). But on the step (Adapt the Back-End Application to Your Database) where one builds the project, it is throwing error.

![image](https://user-images.githubusercontent.com/41268663/97805830-70de3580-1c7e-11eb-8bc9-2dd52a00978c.png)

So I tried the command - **mvn clean package** instead. But this time also it is giving following error.
![image](https://user-images.githubusercontent.com/41268663/97805881-aedb5980-1c7e-11eb-85b8-758cccbbc8f6.png)

Kindly check.
Thanks
Rohit
@jonathanbaker7

**Comment by grenik** [comment]
Hi Rohit,

#### Regarding the first issue:
It turned out that the build command from the guide works only in the default Windows Command Prompt (`cmd.exe`):
```
mvn clean package -Dmaven.test.skip=true
```

If you are using PowerShell, you need to adapt the command slightly:
```
mvn clean package "-Dmaven.test.skip=true"
```

You can also launch Command Prompt in your PowerShell and then execute the first command:
![image](https://user-images.githubusercontent.com/39084120/97852725-690ea780-1cf7-11eb-977e-34c49deebe04.png)

#### Regarding the second issue:

It looks like there is something wrong with the prerequisites on your machine. Please note that to build the project you must have JDK 1.**8**.x (Java **8**) and not a later/earlier version. In other words you may not be able to build the project with Java 11, Java 9 or Java 7.

Could you please run the `mvn -v` command in the command line or PowerShell and paste the output here?

It should look something like:
```
Apache Maven 3.5.2 (138edd61fd100ec658bfa2d307c43b76940a5d7d; 2017-10-18T09:58:13+02:00)
Maven home: C:\maven\home\does\not\matter\..
Java version: 1.8.0_121, vendor: Oracle Corporation
Java home: C:\PROGRA~1\Java\JDK18~1.0_1\jre
```

If the Java version is not 1.8.x, please install the JDK 1.8 (links are in the [README](https://github.com/SAP-samples/s4hana-ext-migrate-historical-data#requirements)) and adapt your `%JAVA_HOME%` and `%PATH%` environment variables to reflect the JDK 1.8 installation.

Please let me know if it helps.

Best regards,
Nikolay

**Comment by I044433** [comment]
Thanks Nikolay, it worked with cmd.exe
